### ISSUE TITLE
The parameter app_id is required

### ISSUE THREAD

**Issue by tnaffh** [iluminar/fluent-facebook#4]
I just pooled in the fluent-facebook, set my FB_APP_ID and SECRET i my .env, did everything else according to the doc but when I hit my login button I get this facebook error:
`The parameter app_id is required` in the broser
Help please

**Comment by Hasnayeen** [comment]
did you published the config files? if not run below command and checck the config file exists in config folder
php artisan vendor:publish --force

**Comment by tnaffh** [comment]
I published the configs, the config exisits

**Comment by Hasnayeen** [comment]
fixed the bug, get the latest code

**Comment by tnaffh** [comment]
Great, but did you update for composer? I cant get the new update via composer

**Comment by Hasnayeen** [comment]
Yeah i did, try again

**Comment by tnaffh** [comment]
Cool, thanks man.
